name = "namweb"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[env.production]
workers_dev = false
route = "namlamron.com/*"

[env.development]
workers_dev = true

# KV Namespace for storing Twitch tokens
[[kv_namespaces]]
binding = "TWITCH_TOKENS"
id = "2977936dd67745eba8216db6a0ca1579" 